package Interfaz;
import dominio.*;
import java.util.*;
import javax.swing.JOptionPane;


public class VentanaIngresoPaquetes extends javax.swing.JFrame implements Observer{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaIngresoPaquetes.class.getName());
    private Sistema sistema;
    /**
     * Creates new form VentanaIngresoPaquetes
     */
    public VentanaIngresoPaquetes(Sistema unSistema) {
        initComponents();
        sistema = unSistema;
        sistema.addObserver(this);
        objetoAPantalla();
    }

    @Override
    public void update(Observable o, Object arg) {
        objetoAPantalla();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdentificador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCliente = new javax.swing.JList<>();
        txtClienteElegido = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDestinatario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnCosto = new javax.swing.JButton();
        txtCosto = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        cbxDepartamento = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(txtIdentificador);
        txtIdentificador.setBounds(160, 20, 71, 22);

        jLabel1.setText("Identificador del paquete");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 150, 16);

        lstCliente.addListSelectionListener(this::lstClienteValueChanged);
        jScrollPane1.setViewportView(lstCliente);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 160, 170);

        txtClienteElegido.setEditable(false);
        txtClienteElegido.addActionListener(this::txtClienteElegidoActionPerformed);
        jPanel1.add(txtClienteElegido);
        txtClienteElegido.setBounds(30, 70, 160, 22);
        jPanel1.add(txtFecha);
        txtFecha.setBounds(360, 110, 90, 22);

        jLabel2.setText("Fecha");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 110, 31, 16);

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(310, 190, 50, 16);
        jPanel1.add(txtDestinatario);
        txtDestinatario.setBounds(360, 190, 90, 22);

        jLabel4.setText("Dirección");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 250, 60, 16);
        jPanel1.add(txtDireccion);
        txtDireccion.setBounds(360, 250, 90, 22);

        jLabel5.setText("Departamento");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 220, 90, 16);

        jLabel6.setText("Peso del paquete (gramos)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 80, 150, 16);
        jPanel1.add(txtPeso);
        txtPeso.setBounds(360, 80, 90, 22);

        jLabel7.setText("DATOS DEL DESTINATARIO");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(290, 160, 150, 16);

        btnCosto.setText("Calcular Costo");
        btnCosto.addActionListener(this::btnCostoActionPerformed);
        jPanel1.add(btnCosto);
        btnCosto.setBounds(480, 80, 120, 23);

        txtCosto.setEditable(false);
        jPanel1.add(txtCosto);
        txtCosto.setBounds(480, 110, 120, 22);

        btnConfirmar.setText("Confirmar\n ingreso");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);
        jPanel1.add(btnConfirmar);
        btnConfirmar.setBounds(480, 190, 130, 80);

        cbxDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artigas", "Canelones", "Cerro Largo", "Colonia", "Durazno", "Flores", "Florida", "Lavalleja", "Maldonado", "Montevideo", "Paysandú", "Río Negro", "Rivera", "Rocha", "Salto", "San José", "Soriano", "Tacuarembó", "Treinta y Tres" }));
        jPanel1.add(cbxDepartamento);
        cbxDepartamento.setBounds(360, 220, 105, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        
        String fecha = txtFecha.getText();
        String nombreDest = txtDestinatario.getText();
        String direccionDest = txtDireccion.getText();
        String identificador = txtIdentificador.getText();
        String departamento = "" + cbxDepartamento.getSelectedItem();
        Cliente cliente = (Cliente) lstCliente.getSelectedValue();
        int peso = 0;
        int precioFinal = 0;
        boolean validaPeso = false;
        
        if (nombreDest.length()!=0 && direccionDest.length()!=0 && identificador.length()!=0  && cliente != null)
        { 
         if(!sistema.existeIdPaquete(identificador))
         {
          try {
        peso = Integer.parseInt(txtPeso.getText());
        precioFinal = Tarifa.valorActual(departamento, peso);
        txtCosto.setText("" + precioFinal);
        validaPeso = true;
        } catch (NumberFormatException e){JOptionPane.showMessageDialog(this,"Debe ingresar un número entero en el peso");}
        
        if (validaPeso)
        {  
          if (validaPeso && fecha.length() == 10 && fecha.charAt(2) == '/' && fecha.charAt(5) == '/' )   
          {
             try {

                   Integer.parseInt(fecha.substring(0,2));
                   Integer.parseInt(fecha.substring(3,5));
                   Integer.parseInt(fecha.substring(6,10));
                   Paquete paquete = new Paquete (identificador, cliente, fecha, nombreDest, direccionDest, departamento, peso, precioFinal, "Pendiente");
                   sistema.agregarPaquete(paquete);
                   JOptionPane.showMessageDialog(this, "El paquete ha sido ingresado");
                   
                  }
             catch (NumberFormatException e){JOptionPane.showMessageDialog(this, "Formato de fecha no válido");}
           } else {JOptionPane.showMessageDialog(this, "Formato de fecha no válido (dd/mm/aaaa)");}
        }  } else {JOptionPane.showMessageDialog(this, "Debe ingresar un Id de paquete no existente");}
        } else {JOptionPane.showMessageDialog(this, "Debe completar todos los campos");}
        
    }//GEN-LAST:event_btnConfirmarActionPerformed
        
    private void lstClienteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstClienteValueChanged
        
        Cliente clienteSeleccionado = (Cliente) lstCliente.getSelectedValue();

        if (clienteSeleccionado != null) {
        txtClienteElegido.setText(clienteSeleccionado.getNombre());}
    }//GEN-LAST:event_lstClienteValueChanged

    private void btnCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCostoActionPerformed
        
        
        String departamento = "" + cbxDepartamento.getSelectedItem();
        
        try {
        int peso = Integer.parseInt(txtPeso.getText());
        int precioFinal = Tarifa.valorActual(departamento, peso);
        txtCosto.setText("" + precioFinal);
        } catch (NumberFormatException e){JOptionPane.showMessageDialog(this,"Debe ingresar un número entero en el peso");}
        Tarifa.setTarifas();
        
        
        
    }//GEN-LAST:event_btnCostoActionPerformed

    private void txtClienteElegidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteElegidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteElegidoActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnCosto;
    private javax.swing.JComboBox<String> cbxDepartamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Object> lstCliente;
    private javax.swing.JTextField txtClienteElegido;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables


  public void objetoAPantalla (){
      
       
       lstCliente.setListData(sistema.getClientes().toArray());
       txtClienteElegido.setText("");



  }

}
