/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import dominio.Cliente;
import dominio.Sistema;
import javax.swing.JOptionPane;
import java.util.*;

/**
 *
 * @author marti
 */
public class VentanaCliente extends javax.swing.JFrame implements Observer{
    
    private Sistema sistema;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaCliente.class.getName());

    /**
     * Creates new form VentanaCliente
     */
    public VentanaCliente(Sistema unSistema) {
    initComponents();
    this.sistema = unSistema;

    this.sistema.addObserver(this);

     objetoAPantalla();
    }

    @Override
    public void update(Observable o, Object arg) {
         objetoAPantalla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCliente = new javax.swing.JList<>();
        txtNombre = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CLIENTES");

        jPanel1.setLayout(null);

        lstCliente.addListSelectionListener(this::lstClienteValueChanged);
        jScrollPane1.setViewportView(lstCliente);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(180, 160, 210, 150);

        txtNombre.addActionListener(this::txtNombreActionPerformed);
        jPanel1.add(txtNombre);
        txtNombre.setBounds(181, 70, 210, 22);
        jPanel1.add(txtCelular);
        txtCelular.setBounds(180, 100, 210, 22);
        jPanel1.add(txtCorreo);
        txtCorreo.setBounds(180, 130, 210, 22);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        jPanel1.add(btnModificar);
        btnModificar.setBounds(180, 320, 100, 23);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);
        jPanel1.add(btnAgregar);
        btnAgregar.setBounds(290, 320, 100, 23);

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 70, 70, 16);

        jLabel2.setText("Celular");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 100, 50, 16);

        jLabel3.setText("Correo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 130, 50, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        setBounds(0, 0, 582, 437);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       String nombre = txtNombre.getText();
       String celular = txtCelular.getText();
       String correo = txtCorreo.getText();
       
       if (!this.sistema.existeNombre(nombre) && this.sistema.correoValido(correo) && !nombre.equals("")){
       
       Cliente cliente = new Cliente (nombre, celular, correo);
       this.sistema.agregarCliente(cliente);} 
       
       else { JOptionPane.showMessageDialog(this, "Correo no valido o nombre repetido");}
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void lstClienteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstClienteValueChanged
        
        Cliente clienteSeleccionado = (Cliente) lstCliente.getSelectedValue();

        if (clienteSeleccionado != null) {
        txtNombre.setText(clienteSeleccionado.getNombre());
        txtCelular.setText(clienteSeleccionado.getCelular());
        txtCorreo.setText(clienteSeleccionado.getCorreo());
}
    }//GEN-LAST:event_lstClienteValueChanged

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
                                                     

     Cliente clienteSeleccionado = (Cliente) lstCliente.getSelectedValue();

    if (clienteSeleccionado == null) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente de la lista");
    } else {

        String nombreNuevo = txtNombre.getText();
        String celularNuevo = txtCelular.getText();
        String correoNuevo = txtCorreo.getText();

        if (nombreNuevo.equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre");
        } else {

            String nombreAnterior = clienteSeleccionado.getNombre();

            if (this.sistema.existeNombre(nombreNuevo) && !nombreNuevo.equals(nombreAnterior)) {
                JOptionPane.showMessageDialog(this, "Ya existe un cliente con ese nombre");
            } else {

                clienteSeleccionado.setNombre(nombreNuevo);
                clienteSeleccionado.setCelular(celularNuevo);
                clienteSeleccionado.setCorreo(correoNuevo);

                cargarLista();

                txtNombre.setText("");
                txtCelular.setText("");
                txtCorreo.setText("");

                lstCliente.clearSelection();

                JOptionPane.showMessageDialog(this, "Cliente modificado correctamente");
                sistema.setClientes(sistema.getClientes());
            }
        }
    }

    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Object> lstCliente;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

public void cargarLista() {
    Collections.sort(this.sistema.getClientes(), Comparator.comparing(Cliente::getNombre));

    Cliente[] clientes = new Cliente[this.sistema.getClientes().size()];

    int i = 0;

    while (i < this.sistema.getClientes().size()) {
        clientes[i] = this.sistema.getClientes().get(i);
        i++;
    }

    lstCliente.setListData(clientes);
}
    
     
 public void objetoAPantalla ()
 {
  cargarLista();
  txtNombre.setText("");
  txtCelular.setText("");
  txtCorreo.setText("");
  
 }

}
