/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import dominio.Funcionario;
import dominio.Sistema;
import javax.swing.JOptionPane;
import java.util.Collections;
import java.util.Comparator;

/**
 *
 * @author felipe
 */
public class VentanaFuncionario extends javax.swing.JFrame {
    
    private Sistema sistema;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaFuncionario.class.getName());

    /**
     * Creates new form VentanaFuncionario
     */
    public VentanaFuncionario(Sistema unSistema) {
        initComponents();
        this.sistema = unSistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNombre = new javax.swing.JLabel();
        btnCelular = new javax.swing.JLabel();
        btnNumFuncionario = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtNumFuncionario = new javax.swing.JTextField();
        VentanaClienteLista = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFuncionario = new javax.swing.JList<>();
        btnNumFuncionario1 = new javax.swing.JLabel();
        txtCorreo1 = new javax.swing.JTextField();
        txtAños = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnNombre.setText("Nombre:");

        btnCelular.setText("Celular:");

        btnNumFuncionario.setText("Numero Funcionario:");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        txtCelular.addActionListener(this::txtCelularActionPerformed);

        btnAgregar.setText("Agegar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        jPanel1.setLayout(null);

        txtNumFuncionario.addActionListener(this::txtNumFuncionarioActionPerformed);

        VentanaClienteLista.setText("Lista:");

        lstFuncionario.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstFuncionario.addListSelectionListener(this::lstFuncionarioValueChanged);
        jScrollPane1.setViewportView(lstFuncionario);

        btnNumFuncionario1.setText("años ingresados:");

        txtCorreo1.addActionListener(this::txtCorreo1ActionPerformed);

        txtAños.addActionListener(this::txtAñosActionPerformed);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVolver)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCelular)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNumFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(VentanaClienteLista)
                                        .addGap(52, 52, 52)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNumFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btnModificar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAgregar))
                                            .addComponent(txtAños, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(6, 6, 6)))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(289, Short.MAX_VALUE)
                    .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(134, 134, 134)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCelular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumFuncionario))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNumFuncionario1)
                    .addComponent(txtAños, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VentanaClienteLista)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(159, 159, 159)
                    .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(258, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = txtNombre.getText();
        String celular = txtCelular.getText();

        int numeroFuncionario = Integer.parseInt(txtNumFuncionario.getText());
        int añoIngreso = Integer.parseInt(txtAños.getText());
        
        if (!this.sistema.existeNombre(nombre)) {

            Funcionario funcionario = new Funcionario(nombre, celular, numeroFuncionario, añoIngreso);
            this.sistema.agregarFuncionario(funcionario);
            cargarLista();
            txtNombre.setText("");
            txtCelular.setText("");
            txtNumFuncionario.setText("");
            txtAños.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Ya existe una persona con ese nombre");
        }   
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNumFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumFuncionarioActionPerformed

    private void txtCorreo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreo1ActionPerformed

    private void txtAñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAñosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñosActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void lstFuncionarioValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstFuncionarioValueChanged
        String nombreSeleccionado = lstFuncionario.getSelectedValue();

        if (nombreSeleccionado != null) {

            int i = 0;
            Funcionario funcionario = null;

            while (i < this.sistema.getFuncionarios().size() && funcionario == null) {

                Funcionario aux = this.sistema.getFuncionarios().get(i);

                if (aux.getNombre().equals(nombreSeleccionado)) {
                    funcionario = aux;
                }

                i = i + 1;
            }

            if (funcionario != null) {

                txtNombre.setText(funcionario.getNombre());
                txtCelular.setText(funcionario.getCelular());
                txtNumFuncionario.setText(String.valueOf(funcionario.getNumeroFuncionario()));
                txtAños.setText(String.valueOf(funcionario.getAñoIngreso()));
            }
        }
    }//GEN-LAST:event_lstFuncionarioValueChanged

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        String nombreSeleccionado = lstFuncionario.getSelectedValue();

        if (nombreSeleccionado != null) {

            String nombreNuevo = txtNombre.getText();

            boolean encontrado = false;
            int i = 0;

            while (i < this.sistema.getFuncionarios().size() && !encontrado) {

                Funcionario funcionario = this.sistema.getFuncionarios().get(i);

                if (funcionario.getNombre().equals(nombreSeleccionado)) {

                    if (!this.sistema.existeNombreDistinto(nombreNuevo,
                            nombreSeleccionado)) {

                        funcionario.setNombre(nombreNuevo);
                        funcionario.setCelular(txtCelular.getText());
                        funcionario.setNumeroFuncionario(Integer.parseInt(txtNumFuncionario.getText()));
                        funcionario.setAñoIngreso(Integer.parseInt(txtAños.getText()));

                        encontrado = true;

                    } else {

                        JOptionPane.showMessageDialog(this,"Ya existe una persona con ese nombre");
                    }
                }

                i = i + 1;
            }

            cargarLista();

            txtNombre.setText("");
            txtCelular.setText("");
            txtNumFuncionario.setText("");
            txtAños.setText("");

            lstFuncionario.clearSelection();
        }

    }//GEN-LAST:event_btnModificarActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VentanaClienteLista;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel btnCelular;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel btnNombre;
    private javax.swing.JLabel btnNumFuncionario;
    private javax.swing.JLabel btnNumFuncionario1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstFuncionario;
    private javax.swing.JTextField txtAños;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumFuncionario;
    // End of variables declaration//GEN-END:variables
    public void cargarLista() {

        //sirve para ordenar por Años, lo saque de chatGPT - Revisar
        Collections.sort(this.sistema.getFuncionarios(),
            Comparator.comparingInt(Funcionario::getAñoIngreso).reversed());
        
        String[] funcionarios = new String[this.sistema.getFuncionarios().size()];

        int i = 0;

        while (i < this.sistema.getFuncionarios().size()) {

            funcionarios[i] = this.sistema.getFuncionarios().get(i).toString();

            i = i + 1;
        }

        lstFuncionario.setListData(funcionarios);
    }   

}
