package Interfaz;

import dominio.*;
import javax.swing.JOptionPane;
import java.util.*;

/**
 *
 * @author felipe
 */
public class VentanaFuncionario extends javax.swing.JFrame implements Observer{
    
    private Sistema sistema;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaFuncionario.class.getName());

    /**
     * Creates new form VentanaFuncionario
     */
    public VentanaFuncionario(Sistema unSistema) {
        initComponents();
        this.sistema = unSistema;
        sistema.addObserver(this);
        objetoAPantalla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNombre = new javax.swing.JLabel();
        btnCelular = new javax.swing.JLabel();
        btnNumFuncionario = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtNumFuncionario = new javax.swing.JTextField();
        VentanaClienteLista = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFuncionario = new javax.swing.JList<>();
        btnNumFuncionario1 = new javax.swing.JLabel();
        txtCorreo1 = new javax.swing.JTextField();
        txtAños = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FUNCIONARIOS");

        btnNombre.setText("Nombre:");

        btnCelular.setText("Celular:");

        btnNumFuncionario.setText("Funcionario:");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        txtCelular.addActionListener(this::txtCelularActionPerformed);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        jPanel1.setLayout(null);

        txtNumFuncionario.addActionListener(this::txtNumFuncionarioActionPerformed);

        VentanaClienteLista.setText("Lista:");

        lstFuncionario.addListSelectionListener(this::lstFuncionarioValueChanged);
        jScrollPane1.setViewportView(lstFuncionario);

        btnNumFuncionario1.setText("Año de ingreso:");

        txtCorreo1.addActionListener(this::txtCorreo1ActionPerformed);

        txtAños.addActionListener(this::txtAñosActionPerformed);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnVolver)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(VentanaClienteLista)
                                                .addGap(52, 52, 52))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnCelular)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnNumFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnNumFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAños, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(250, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(244, Short.MAX_VALUE)
                    .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(134, 134, 134)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCelular))
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAños, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnAgregar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VentanaClienteLista)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver)
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(159, 159, 159)
                    .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(277, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        String nombre = txtNombre.getText();
        String celular = txtCelular.getText();
        int numeroFuncionario;
        int añoIngreso;
        try 
        { 
              numeroFuncionario = Integer.parseInt(txtNumFuncionario.getText());
              añoIngreso = Integer.parseInt(txtAños.getText());
         ;
        if (!this.sistema.existeNombre(nombre)) {

            Funcionario funcionario = new Funcionario(nombre, celular, numeroFuncionario, añoIngreso);
            this.sistema.agregarFuncionario(funcionario);
            
        } else {
            JOptionPane.showMessageDialog(this, "Ya existe una persona con ese nombre");
        }   
        }
        catch (Exception e){JOptionPane.showMessageDialog(this, "Debe ingresar un número entero en el tercer y cuarto campo");}
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    @Override
    public void update(Observable o, Object arg) 
    {   objetoAPantalla();    }

    
    private void txtNumFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumFuncionarioActionPerformed

    private void txtCorreo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreo1ActionPerformed

    private void txtAñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAñosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñosActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void lstFuncionarioValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstFuncionarioValueChanged
       
        Funcionario funcionario = (Funcionario) lstFuncionario.getSelectedValue();

        if (funcionario != null) {

                txtNombre.setText(funcionario.getNombre());
                txtCelular.setText(funcionario.getCelular());
                txtNumFuncionario.setText(String.valueOf(funcionario.getNumeroFuncionario()));
                txtAños.setText(String.valueOf(funcionario.getAñoIngreso()));
            }
        
    }//GEN-LAST:event_lstFuncionarioValueChanged

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        Funcionario funcionario = (Funcionario) lstFuncionario.getSelectedValue();
                
        if (funcionario != null) {
           
            String nombreAnterior = funcionario.getNombre();
            String nombreNuevo = txtNombre.getText();
            String cel = txtCelular.getText();
            String añoIngreso = txtAños.getText();
            String numFuncionario = txtNumFuncionario.getText();
           

            if ((this.sistema.existeNombre(nombreNuevo) && !nombreAnterior.equals(nombreNuevo)) || !Funcionario.sonEnterosValidos(numFuncionario, añoIngreso))
            { JOptionPane.showMessageDialog(this, "Nombre repetido o numeros invalidos");}
               
                
            else {
               
               int año = Integer.parseInt(añoIngreso);
               int num = Integer.parseInt(numFuncionario);
                 
                funcionario.setNombre(nombreNuevo);
                funcionario.setCelular(cel);
                funcionario.setAñoIngreso(año);
                funcionario.setNumeroFuncionario(num);
               
                
                sistema.setClientes(sistema.getClientes());
                lstFuncionario.clearSelection();}
            
            
        }

    }//GEN-LAST:event_btnModificarActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VentanaClienteLista;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel btnCelular;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel btnNombre;
    private javax.swing.JLabel btnNumFuncionario;
    private javax.swing.JLabel btnNumFuncionario1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Object> lstFuncionario;
    private javax.swing.JTextField txtAños;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumFuncionario;
    // End of variables declaration//GEN-END:variables
    
    public void cargarLista() {
        
        //sirve para ordenar por Años, lo saque de chatGPT - Revisar
        //LO MODIFIQUE UN POCO, ESTABA CARGANDO ARRAYLIST DE STRING Y LO PASE A ARRYLISTA DE FUNCIONARIO
        // DESPUES LO TERMINO IGUAL PORQUE FALTA QUE SE ORDENE BIEN, ES METERLE UN CRITERIO EN LA CLASE FUNCIONARIO
        
        Collections.sort(this.sistema.getFuncionarios(),
            Comparator.comparingInt(Funcionario::getAñoIngreso).reversed());
        
        Funcionario [] funcionarios = new Funcionario [this.sistema.getFuncionarios().size()];

        int i = 0;

        while (i < this.sistema.getFuncionarios().size()) {

            funcionarios[i] = this.sistema.getFuncionarios().get(i);

            i = i + 1;
        }

        lstFuncionario.setListData(funcionarios);
    }   
    
public void objetoAPantalla ()
{          
            cargarLista();
            txtNombre.setText("");
            txtCelular.setText("");
            txtNumFuncionario.setText("");
            txtAños.setText("");

}
}

