package Interfaz;
import dominio.*;

public class VentanaPaquetes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPaquetes.class.getName());
    private Sistema sistema;
    /**
     * Creates new form VentanaPaquetes
     */
    public VentanaPaquetes (Sistema unSistema) {
    initComponents();
    this.sistema = unSistema;
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIngresoPaquetes = new javax.swing.JButton();
        btnEnvioPaquetes = new javax.swing.JButton();
        btnRecepcionPaquetes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paquetes");

        btnIngresoPaquetes.setText("Ingreso");
        btnIngresoPaquetes.addActionListener(this::btnIngresoPaquetesActionPerformed);

        btnEnvioPaquetes.setText("Envio");
        btnEnvioPaquetes.addActionListener(this::btnEnvioPaquetesActionPerformed);

        btnRecepcionPaquetes.setText("Recepción");
        btnRecepcionPaquetes.addActionListener(this::btnRecepcionPaquetesActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresoPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRecepcionPaquetes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnvioPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnIngresoPaquetes)
                .addGap(18, 18, 18)
                .addComponent(btnEnvioPaquetes)
                .addGap(18, 18, 18)
                .addComponent(btnRecepcionPaquetes)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoPaquetesActionPerformed
        
        VentanaIngresoPaquetes ventana = new VentanaIngresoPaquetes(this.sistema);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_btnIngresoPaquetesActionPerformed

    private void btnEnvioPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvioPaquetesActionPerformed
        VentanaEnvio ventana = new VentanaEnvio(this.sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnEnvioPaquetesActionPerformed

    private void btnRecepcionPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecepcionPaquetesActionPerformed
        VentanaRecepcion ventana = new VentanaRecepcion(this.sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnRecepcionPaquetesActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnvioPaquetes;
    private javax.swing.JButton btnIngresoPaquetes;
    private javax.swing.JButton btnRecepcionPaquetes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
